[client]
showSidebarNavigation = false

[theme]
base="dark"
primaryColor="#66FCF1"
backgroundColor="#0B0C10"
secondaryBackgroundColor="#1F2833"
textColor="#C5C6C7"

[server]
enableStaticServing = true